#!/bin/bash
export DEBUG="True"
export AWS_REGION="eu-west-1"
export S3_TMB_DATA="tmb-datalake-stageduy"
export S3_URL="https://s3-eu-west-1.amazonaws.com/"
export S3_CACHE="tmb-search-result"
export REAL_TIME_TABLE="tmb-realtime-stageDuy"
export REQUESTS_TABLE="user-request"
# export AWS_PROFILE="development"
echo "Done"
